### PR TITLE
Explicitly pass arguments to constructor

### PR DESCRIPTION
**Pull request by erlikh**
Hey guys, I'm working on the Gulp runner for the Pioneer. The change will make it possible to start Pioneer form code, without CLI arguments.

### CODE REVIEW

**Comment by samccone** [comment]
Yeah this seems like a reasonable change 🐙 thanks !

**Comment by samccone** [comment]
:shipit:

**Comment by samccone** [comment]
thanks again @erlikh

**Comment by erlikh** [comment]
:+1:

**Pull request merged**
