### PR TITLE
Sauce source

### PR DESCRIPTION
**Pull request by tomhicks-bsf**
I'm not remotely suggesting this to be a finished pull request, but hopefully it will get the ball rolling...

### CODE REVIEW

**Comment by tomhicks-bsf** [comment]
#304

**Comment by samccone** [comment]
ok this is totally possible with the latest release and the Driver configuration
https://github.com/mojotech/pioneer/blob/master/docs/globals.md#driver-configuration

**Comment by tomhicks-bsf** [comment]
Yeah mate I saw that, nice one. Getting used to the way cucumber allows code injection!



Cheers,Tom

**Comment by samccone** [comment]
yeah it is kinda annoying but whatever it works :dancer:

**Pull request closed without merging**
